apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
data:
  my.cnf: |
    [mysqld]
    default_storage_engine=InnoDB
    innodb_buffer_pool_size={{ .Values.innodb.bufferPoolSize }}
    innodb_log_file_size={{ .Values.innodb.logFileSize }}
    innodb_flush_log_at_trx_commit={{ .Values.innodb.flushLogAtTrxCommit }}
    innodb_file_per_table=1
    innodb_flush_method=O_DIRECT
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections=200
    skip-host-cache
    skip-name-resolve

