apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.auth.rootPassword | quote }}
  mysql-user: {{ .Values.auth.username | quote }}
  mysql-password: {{ .Values.auth.password | quote }}
  mysql-database: {{ .Values.auth.database | quote }}

